export const team_photo = [
  {
    id: 1,
    src: '/photos/subroto/1.jpg',
    name: 'Subroto Koiry',
    post: 'CO-ORDINATOR',
    linkedin: 'www.linkedin.com/in/subroto-koiry',
    gmail: 'koirysubroto@gmail.com',
  },
  {
    id: 2,
    src: '/photos/subroto/1.jpg',
    name: 'Subroto Koiry',
    post: 'CO-ORDINATOR',
    linkedin: 'www.linkedin.com/in/subroto-koiry',
    gmail: 'koirysubroto@gmail.com',
  },
  {
    id: 3,
    src: '/photos/subroto/1.jpg',
    name: 'Subroto Koiry',
    post: 'CO-ORDINATOR',
    linkedin: 'www.linkedin.com/in/subroto-koiry',
    gmail: 'koirysubroto@gmail.com',
  },
  {
    id: 1,
    src: '/photos/subroto/1.jpg',
    name: 'Subroto Koiry',
    post: 'CO-ORDINATOR',
    linkedin: 'www.linkedin.com/in/subroto-koiry',
    gmail: 'koirysubroto@gmail.com',
  },
  {
    id: 2,
    src: '/photos/subroto/1.jpg',
    name: 'Subroto Koiry',
    post: 'CO-ORDINATOR',
    linkedin: 'www.linkedin.com/in/subroto-koiry',
    gmail: 'koirysubroto@gmail.com',
  },
  {
    id: 4,
    src: '/photos/subroto/1.jpg',
    name: 'Subroto Koiry',
    post: 'CO-ORDINATOR',
    linkedin: 'www.linkedin.com/in/subroto-koiry',
    gmail: 'koirysubroto@gmail.com',
  },
]