export const team_photo = [
  {
    id: 1,
    type: 'executive_committee',
    src: '/photos/members/subroto.jpg',
    name: 'Subroto Koiry',
    post: 'CO-ORDINATOR',
    linkedin: 'www.linkedin.com/in/members/subroto.pngry',
    gmail: 'koirysubroto@gmail.com',
  },
  {
    id: 2,
    type: 'executive_committee',
    src: '/photos/members/subroto.jpg',
    name: 'Subroto Koiry',
    post: 'CO-ORDINATOR',
    linkedin: 'www.linkedin.com/in/members/subroto.pngry',
    gmail: 'koirysubroto@gmail.com',
  },
  {
    id: 3,
    type: 'executive_committee',
    src: '/photos/members/subroto.jpg',
    name: 'Subroto Koiry',
    post: 'CO-ORDINATOR',
    linkedin: 'www.linkedin.com/in/members/subroto.pngry',
    gmail: 'koirysubroto@gmail.com',
  },
  {
    id: 4,
    type: 'executive_committee',
    src: '/photos/members/subroto.jpg',
    name: 'Subroto Koiry',
    post: 'CO-ORDINATOR',
    linkedin: 'www.linkedin.com/in/members/subroto.pngry',
    gmail: 'koirysubroto@gmail.com',
  },
  {
    id: 5,
    type: 'executive_committee',
    src: '/photos/members/subroto.jpg',
    name: 'Subroto Koiry',
    post: 'CO-ORDINATOR',
    linkedin: 'www.linkedin.com/in/members/subroto.pngry',
    gmail: 'koirysubroto@gmail.com',
  },
  {
    id: 6,
    type: 'executive_committee',
    src: '/photos/members/subroto.jpg',
    name: 'Subroto Koiry',
    post: 'CO-ORDINATOR',
    linkedin: 'www.linkedin.com/in/members/subroto.pngry',
    gmail: 'koirysubroto@gmail.com',
  },
]